package com.codingshuttle.jpaTutorial.jpaTuts.entities;

import jakarta.persistence.*;
import lombok.*;
import org.hibernate.annotations.CreationTimestamp;
import org.hibernate.annotations.UpdateTimestamp;

import java.math.BigDecimal;
import java.time.LocalDateTime;


@Data
@AllArgsConstructor
@NoArgsConstructor
@Builder
@Entity
@Table(
        name="product_table",
        uniqueConstraints = {
                @UniqueConstraint(name = "sku_unique",columnNames = {"sku"}),   //we want "sku" to be unique and defining a constraint
                @UniqueConstraint(name= "title_price_unique",columnNames = {"title_x","price"})
        },
        indexes = {
                @Index(name = "sku_index",columnList = "sku")
        }
)

public class ProductEntity {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;
    @Column(nullable = false,length = 20) //"sku" wont be null. Hibernate makes sures that sql query that was generated to create this Product Entity makes the "sku" field as not nullable (you cannot give null to "sku" field in database)
    private String sku;//another kind of id
    @Column(name = "title_x")
    private String title;
    private BigDecimal price;
    private Integer quantity;

    @CreationTimestamp
    private LocalDateTime createdAt;
    @UpdateTimestamp
    private LocalDateTime updatedAt;
}



/*
see UniqueConstraint on title and price, it means

Cannot have 2 items whose title and price are same
Ex:
parle 20
parle 50
Accepted ✅

parle 20
parle 20
Not accepted  ❌



Indexes are used to enhance our get queries.
Indexes define the index table with help of algos like btrees,hashtable and will create a short db to gather the data fastly.
Index on "Id" is autogenerated   (we have written on top of "Id")
We can define Index on various columns.


Say we are querying on basis of "sku" lot of times, we want to create an index on "sku"

*/


//explanation from chatgpt. LONG PARA BELOW. FOR QUICK RECAP JUST READ FROM LINE 545-634 enough
/*
when i run the spring boot application with just product entity, and i configured mysql , in console it is giving hibernate sql output as below

Hibernate:
    create table product_table (
        id bigint not null auto_increment,
        created_at datetime(6),
        price decimal(38,2),
        quantity integer,
        sku varchar(20) not null,
        title_x varchar(255),
        updated_at datetime(6),
        primary key (id)
    ) engine=InnoDB
Hibernate:
    create index sku_index
       on product_table (sku)
Hibernate:
    alter table product_table
       drop index sku_unique
Hibernate:
    alter table product_table
       add constraint sku_unique unique (sku)
Hibernate:
    alter table product_table
       drop index title_price_unique
Hibernate:
    alter table product_table
       add constraint title_price_unique unique (title_x, price)



1️⃣ What is happening when you run the app with ONLY this entity?

You have:
@Entity present
MySQL configured
spring.jpa.hibernate.ddl-auto=update (implicitly or explicitly)

➡️ Hibernate scans entities → compares entity metadata with DB → syncs schema
This process is called schema update.


2️⃣ Step-by-step explanation of the SQL you see
✅ Step 1: Hibernate creates the table
create table product_table (
    id bigint not null auto_increment,
    created_at datetime(6),
    price decimal(38,2),
    quantity integer,
    sku varchar(20) not null,
    title_x varchar(255),
    updated_at datetime(6),
    primary key (id)
) engine=InnoDB


Why no unique constraints here yet?
Because:
Hibernate creates table first
Constraints & indexes are added after, in separate steps
This is normal behavior.


✅ Step 2: Hibernate creates your explicit index
create index sku_index on product_table (sku)

This comes from:
indexes = {
    @Index(name = "sku_index", columnList = "sku")
}

✔️ Straightforward.




3️⃣ Now the confusing part: “DROP INDEX” 🤯
❓ Why is Hibernate dropping indexes it just created?

Example:
alter table product_table drop index sku_unique
alter table product_table add constraint sku_unique unique (sku)

🔴 IMPORTANT CONCEPT (MySQL-specific)

👉 In MySQL, a UNIQUE constraint is implemented as a UNIQUE INDEX

There is no separate object called:
“unique constraint”
“unique index”

They are the same thing internally.

🔍 What Hibernate is doing internally
Hibernate wants:
@UniqueConstraint(name = "sku_unique", columnNames = {"sku"})

But MySQL:
Automatically creates a unique index
Names may not match Hibernate’s expected name

So Hibernate does this:
1️⃣ Drop any existing index with that name (defensive step)
drop index sku_unique

Even if:
It doesn’t exist
Or MySQL created one implicitly

2️⃣ Re-create it explicitly with correct definition
add constraint sku_unique unique (sku)
✔️ This guarantees schema consistency



Same logic for composite unique constraint
drop index title_price_unique
add constraint title_price_unique unique (title_x, price)

From:
@UniqueConstraint(
   name="title_price_unique",
   columnNames={"title_x","price"}
)


4️⃣ Why does Hibernate not create unique constraints directly in CREATE TABLE?
Because:
Different DBs behave differently (MySQL, PostgreSQL, Oracle)
Hibernate uses a portable strategy
Constraints are added after table creation for safety





5️⃣ Now your conceptual questions (VERY IMPORTANT)
➤ What are indexes?
Simple definition

An index is a separate data structure that helps the database find rows faster, without scanning the entire table.

Without index (full table scan)
SELECT * FROM product_table WHERE sku='ABC123';


DB does:
Check row 1
Check row 2
Check row 3
…
Check all rows 😵
Time: O(n)

With index on sku
DB:
Looks at index
Finds row address immediately
Jumps directly to that row

Time: O(log n)

➤ How indexes work internally (simplified)
Most common structure: B-Tree
            [SKU M]
           /        \
     [SKU A-F]   [SKU N-Z]
        |             |
   row pointers   row pointers


Index stores:
  Column value (sku)
  Pointer to actual row (disk address)
Tree stays sorted
Fast search, insert, delete


Internally:
Operation	Without Index	With Index
SELECT WHERE	slow	fast
INSERT	fast	slightly slower
UPDATE	fast	slower
DELETE	fast	slower

⚠️ Indexes speed up reads, slow down writes

➤ Why not index every column?
Because:
Index consumes memory
Insert/update cost increases
Too many indexes → performance degradation
👉 Index only frequently queried columns




6️⃣ “Index on id is autogenerated” – what does this mean?
You wrote:
@Id
@GeneratedValue(strategy = GenerationType.IDENTITY)
private Long id;


Hibernate generates:
primary key (id)

In MySQL:
👉 PRIMARY KEY automatically creates a UNIQUE INDEX

So internally MySQL does:
    Primary Key Constraint ✅
    Unique Index on id ✅

Even if you don’t explicitly define it.

That’s why:
“Index on id is autogenerated”
You never wrote @Index — MySQL did it implicitly.


7️⃣ Summary (read this twice)
✔ Prevent confusion

Unique constraint = unique index (in MySQL)
Hibernate drops & re-adds indexes to ensure correctness
ddl-auto=update is schema reconciliation, not blind creation
Primary key always has an index
Indexes speed reads, slow writes






1️⃣ First, the clean mental model (IMPORTANT)
	Constraint = rule
	Index = data structure
They are NOT the same thing, but sometimes one is implemented using the other.

2️⃣ What is a CONSTRAINT?
A constraint is a rule enforced by the database to protect data correctness.
Constraints answer:
	❌ “Is this data allowed or not?”
They do NOT care about performance.

Common constraints
🔹 PRIMARY KEY
Rules:
	• Cannot be NULL
	• Must be UNIQUE
	• Identifies a row

PRIMARY KEY (id)

🔹 UNIQUE
Rules:
	• No two rows can have the same value(s)

UNIQUE (sku)
UNIQUE (title, price)

🔹 NOT NULL
Rules:
	• Value must exist

sku VARCHAR(20) NOT NULL

🔹 FOREIGN KEY
Rules:
	• Value must exist in another table

FOREIGN KEY (order_id) REFERENCES orders(id)

🔹 CHECK
Rules:
	• Value must satisfy condition

CHECK (price > 0)

Key takeaway about constraints
	• They validate data
	• They can reject INSERT / UPDATE
	• They do not help searching

3️⃣ What is an INDEX?
An index is a performance optimization structure.
Indexes answer:
	⚡ “How fast can I find the data?”
Indexes do not validate data correctness.

Example

CREATE INDEX sku_index ON product_table(sku);
What this does:
	• Creates a B-Tree
	• Stores (sku → row_address)
	• Speeds up SELECT WHERE sku = ?

Index properties
	• Improves SELECT
	• Slows INSERT / UPDATE / DELETE
	• Uses extra memory

4️⃣ So why do people mix CONSTRAINT and INDEX?
Because some constraints NEED an index to be enforced efficiently.

5️⃣ The BIG overlap (this is the key confusion)
UNIQUE constraint needs an index
How can the DB check:
	“Is this value already present?”
Without an index:
	• DB must scan entire table ❌
	• Too slow ❌
So databases do this:
	UNIQUE constraint is implemented USING a UNIQUE INDEX

Same for PRIMARY KEY
PRIMARY KEY rules:
	• Unique
	• Not null
So DB does:
	• PRIMARY KEY constraint
	• UNIQUE index automatically

6️⃣ MySQL-specific behavior (IMPORTANT)
In MySQL:
Concept	Separate object?
UNIQUE constraint	❌
UNIQUE index	✅
PRIMARY KEY	Constraint + index
INDEX	Index only
👉 MySQL does not store UNIQUE constraints separately.
👉 It stores them as unique indexes.
That’s why Hibernate SQL shows:

drop index sku_unique
add constraint sku_unique unique (sku)
Internally MySQL:
	• Drops index
	• Creates unique index again
Hibernate speaks standard SQL
MySQL executes index operations

7️⃣ Visual analogy (remember this)
🏛 Constraint = Law
	“Only one person can have this Aadhaar number”
🗂 Index = Filing system
	“Here is a sorted list to quickly check Aadhaar numbers”
Law ≠ filing system
But law uses filing system to enforce itself efficiently.


9️⃣ Can index exist without constraint?
✔ YES

CREATE INDEX sku_index ON product_table(sku);
	• Duplicate values allowed
	• Fast search
	• No data validation

🔟 Can constraint exist without index?
In theory:
✔ YES (logical rule)
In practice:
❌ NO (for UNIQUE / PRIMARY KEY)
DB automatically creates index to enforce it.



1️⃣2️⃣ Why Hibernate drops & recreates indexes
Hibernate wants:
	• Constraint name
	• Column order
	• DB consistency
So it:
	1. Drops old index
	2. Recreates as constraint
	3. MySQL stores it again as index
This is schema synchronization, not duplication.


Why Hibernate drops & recreates indexes (deep but clear)
Hibernate is doing schema reconciliation:
	“What I want the database to look like
	vs
	what the database currently looks like”
If there is any mismatch, Hibernate fixes it.

1️⃣ “Constraint name” — why Hibernate cares
Your entity says:

@UniqueConstraint(
   name = "sku_unique",
   columnNames = {"sku"}
)
This is metadata, not just SQL.
Hibernate internally stores:

Constraint:
- type: UNIQUE
- name: sku_unique
- columns: [sku]

What MySQL might have
When MySQL creates a unique index automatically, it might:
	• Use a different internal name
	• Or treat it as an index, not a constraint
	• Or reuse an old index created earlier
Example:

UNIQUE KEY sku (sku)
Hibernate sees:
❌ Name mismatch
❌ Type mismatch (index vs constraint)
So Hibernate thinks:
	“This is NOT the same constraint I asked for.”
➡️ Drop & recreate

2️⃣ “Column order” — why order matters
Your composite constraint:

@UniqueConstraint(
   name = "title_price_unique",
   columnNames = {"title_x", "price"}
)
Hibernate expects:

UNIQUE (title_x, price)

What if DB has:

UNIQUE (price, title_x)
Logically:
	• Uniqueness rule is the same ❌ (for constraint)
	• Index behavior is NOT the same ❌ (for performance)
Example:

WHERE title_x = 'parle' AND price = 20   -- fast
WHERE price = 20 AND title_x = 'parle'   -- slower
So Hibernate checks:
	• Column list
	• Column order
If order differs → mismatch → drop & recreate.

3️⃣ “DB consistency” — Hibernate’s paranoia (for good reason)
Hibernate supports:
	• MySQL
	• PostgreSQL
	• Oracle
	• SQL Server
	• H2
Each DB:
	• Names constraints differently
	• Handles indexes differently
	• Auto-creates things implicitly
Hibernate follows this rule:
	“If I cannot be 100% sure, I recreate.”
So instead of guessing, Hibernate:
	1. Drops what exists
	2. Creates exactly what entity metadata describes
This avoids:
	• Silent bugs
	• Half-correct schemas
	• Production disasters





!!!!!!!!MOST IMPORTANT!!!!!!:

Step-by-step: YOUR exact SQL sequence
Let’s replay your console output like a movie 🎬

🎬 Scene 1: Table creation

create table product_table ( ... )
✔️ Table exists
❌ No constraints yet

🎬 Scene 2: Index from @Index

create index sku_index on product_table (sku)
✔️ Performance index created

🎬 Scene 3: Unique constraint reconciliation
Hibernate checks DB:
	“Do I already have UNIQUE constraint named sku_unique?”
DB answers:
	“I have an index, not a constraint.”
Hibernate says:
	“Not acceptable.”

🎬 Scene 4: Defensive cleanup

alter table product_table drop index sku_unique
Even if:
	• It doesn’t exist
	• Or exists with different definition
Hibernate is resetting state.

🎬 Scene 5: Correct creation

alter table product_table add constraint sku_unique unique (sku)
MySQL internally:
	• Creates a unique index
	• But now matches Hibernate’s metadata

🎬 Same logic repeats for composite constraint

drop index title_price_unique
add constraint title_price_unique unique (title_x, price)

Very important misconception to kill ❌
	“Hibernate created index → why drop it?”
Because:
	• That index was not created for uniqueness
	• It was created for query performance
	• Unique constraint requires guaranteed uniqueness rule
Different purpose → different metadata → rebuild.



✅ Your understanding — verified & refined

✔️ Correct (with precision)
	• PRIMARY KEY = NOT NULL + UNIQUE (rule-wise)
	• To enforce UNIQUE efficiently, the database creates an index
	• Therefore:
	✅ Primary Key is ALWAYS backed by an index
In MySQL (and most DBs):
	• PRIMARY KEY → unique index automatically created
	• You cannot have a primary key without an index
✔️ Your reasoning is solid.

🔹 Your statement:
	Though unique constraint and unique index are same, to match the metadata, it drops existing index and creates unique constraint which again internally uses unique index only.
✔️ Correct (minor wording fix)
Better wording:
	Though unique constraint and unique index are different concepts,
	MySQL implements a unique constraint USING a unique index.
	Hibernate drops the existing index if it doesn’t match metadata and recreates the unique constraint,
	which MySQL again stores internally as a unique index.

⚠️ One tiny clarification (important but small)
❌ “unique constraint and unique index are same” — not conceptually
✅ They are implemented the same way in MySQL
Correct mental model:
Layer	Meaning
SQL / JPA	UNIQUE constraint = rule
Database engine	Unique index = mechanism
MySQL	Stores constraint as index
Hibernate lives at rule level
MySQL executes at mechanism level

🧠 Final corrected one-liner (memorize this)
	Primary key is always indexed because it enforces uniqueness.
	Unique constraints are enforced using unique indexes.
	Hibernate recreates them to match metadata, and MySQL stores them again as indexes.



DOUBT2:
Instead of constraint can i use validation somehow and make sure there can by only one "sku"?

Short answer (clear & honest)
	❌ No — validation alone is NOT sufficient to guarantee only one sku.
You can use validation, but you MUST still use a database constraint.
Validation ≠ Guarantee.

Why this doubt comes naturally
You’re thinking:
	“If I check in code before saving,
	why do I need a DB constraint?”
That sounds reasonable — until concurrency enters the picture.
Let’s break it.

1️⃣ What “validation” means in practice
Example validation in Spring:

if (productRepository.existsBySku(sku)) {
    throw new RuntimeException("SKU already exists");
}
productRepository.save(product);
Or with Bean Validation:

@NotNull
private String sku;
Or even a custom validator.

What validation does well
✔️ Gives nice error messages
✔️ Catches issues early
✔️ Improves user experience

What validation CANNOT guarantee
❌ Uniqueness under concurrency
❌ Protection from multiple app instances
❌ Protection from direct DB access
❌ Absolute data integrity

2️⃣ The fatal problem: race conditions 💥
Scenario (VERY REAL)
Two users hit your API at the same time:

Thread A                   Thread B
---------                  ---------
existsBySku("ABC") → false
                            existsBySku("ABC") → false
save("ABC")
                            save("ABC")
Result:

ABC
ABC   ❌ duplicate
Your validation passed.
Your data is now corrupted.

Why this happens
Because:
	• Validation runs outside the database
	• Database is the only shared authority
	• App-level checks are not atomic

3️⃣ Database constraint = final authority
When you define:

UNIQUE (sku)
The database guarantees:
	“No matter WHO inserts
	No matter HOW
	No matter WHEN
	there will be only ONE sku.”
Even if:
	• 100 concurrent requests
	• Multiple app servers
	• Manual SQL inserts
✔️ Absolute guarantee.

4️⃣ Correct architecture (this is the key)
✅ Use BOTH
Layer	Responsibility
Validation	User-friendly feedback
Constraint	Data integrity guarantee

Typical professional setup
Entity

@Column(nullable = false, unique = true)
private String sku;
Service

if (repo.existsBySku(sku)) {
    throw new IllegalArgumentException("SKU already exists");
}
DB

UNIQUE (sku)

5️⃣ What happens when both are used?
	1. Validation catches most cases early
	2. Constraint catches edge cases (race conditions)
	3. App catches DB exception and maps it to clean error
Example:

catch (DataIntegrityViolationException e) {
    throw new DuplicateSkuException();
}

6️⃣ Can validation replace constraint?
❌ Never for uniqueness
Validation can replace:
	• NOT NULL
	• Length checks
	• Format checks (regex)
Validation CANNOT replace:
	• UNIQUE
	• PRIMARY KEY
	• FOREIGN KEY







*/